Repository InShine-Studios/Horror-3D, pull requests merged in 2022-02, with the labels that each got.

#161 [feature] NPC interaction dialog box
  Assets/Astralization/Characters/NPC.meta
  Assets/Astralization/Characters/NPC/NPC.prefab
  Assets/Astralization/Characters/NPC/NPC.prefab.meta
  Assets/Astralization/Scripts/Interactables/Controller/NpcController.cs
  Assets/Astralization/Scripts/Interactables/Controller/NpcController.cs.meta
  Assets/Astralization/Scripts/Player/PlayerMovement.cs
  Assets/Astralization/Scripts/UI/DialogueManager.cs
  Assets/Astralization/Scripts/UI/DialogueManager.cs.meta
  Assets/Astralization/Tests/InteractableTest/InteractableTestScene.unity
  Assets/Astralization/Tests/NpcTest.meta
  Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
  Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs.meta
  Assets/Astralization/Tests/NpcTest/NpcInteractableTestScene.unity.meta
  Assets/Astralization/UI/DialogueBox.meta
  Assets/Astralization/UI/DialogueBox/Dialogue Box.controller
  Assets/Astralization/UI/DialogueBox/Dialogue Box.controller.meta
  Assets/Astralization/UI/DialogueBox/Dialogue.prefab
  Assets/Astralization/UI/DialogueBox/Dialogue.prefab.meta
  Assets/Astralization/UI/DialogueBox/DialogueBoxClose.anim
  Assets/Astralization/UI/DialogueBox/DialogueBoxClose.anim.meta
  Assets/Astralization/UI/DialogueBox/DialogueBoxOpen.anim
  Assets/Astralization/UI/DialogueBox/DialogueBoxOpen.anim.meta
  Assets/Input System/PlayerInputActions.inputactions
  Assets/_Developers/Uci/House Abigail Wall.unity
  Assets/_Developers/Uci/House Abigail Wall.unity.meta
  Assets/_Developers/Uci/HouseAbigail_Adjustment 1.unity
  Assets/_Developers/Uci/HouseAbigail_Adjustment 1.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: Designing :books:, Programming :computer:

#163 [feature] Implement audio heart beat and dying scream
  Assets/Astralization/Gameplay/EnemyCharacters.meta
  Assets/Astralization/Gameplay/PlayerCharacters.meta
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_FemaleScream_1.mp3
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_FemaleScream_1.mp3.meta
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_Heartbeat_1_Loop.mp3
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_Heartbeat_1_Loop.mp3.meta
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_Heartbeat_2_Loop.mp3
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_Heartbeat_2_Loop.mp3.meta
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_Heartbeat_3_Loop.mp3
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_Heartbeat_3_Loop.mp3.meta
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_MaleScream_1.mp3
  Assets/Astralization/Gameplay/PlayerCharacters/SFX_PlayerGameplay_PlayerBehavior_MaleScream_1.mp3.meta
Labels: Audio :headphones:

#165 [Feature] Add Outdoor For House Abigail
  Assets/Astralization/_Levels/Maps/HouseAbigail_Adjustment_Outdoor.unity
  Assets/Astralization/_Levels/Maps/HouseAbigail_Adjustment_Outdoor.unity.meta
  Assets/_Developers/Uci/HouseAbigail_Adjustment_Outdoor 1.unity
  Assets/_Developers/Uci/HouseAbigail_Adjustment_Outdoor 1.unity.meta
Labels: Designing :books:

#168 [refactor] closest item
  Assets/Astralization/Scripts/Player/Detectors/ObjectDetector.cs
  Assets/Astralization/Tests/InteractableTest/ItemTest.cs
Labels: Programming :computer:

#185 Add Sprite to Unity
  Assets/Astralization/Characters/Herc.meta
  Assets/Astralization/Characters/Herc/T_CH_Herc.png
  Assets/Astralization/Characters/Herc/T_CH_Herc.png.meta
Labels: Assets :art:

#190 [feature] Exorcism Item + Channeling + HUD
  Assets/Astralization/Characters/Player/Iris/Iris.prefab
  Assets/Astralization/Gameplay/Interactables/Items/Exorcism Item.meta
  Assets/Astralization/Gameplay/Interactables/Items/Exorcism Item/ExorcismItem.prefab.meta
  Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
  Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs.meta
  Assets/Astralization/Scripts/Interactables/Item/Item.cs
  Assets/Astralization/Scripts/Managers/GameManager.cs
  Assets/Astralization/Scripts/Player/InputHandler/ExorcismInputHandler.cs
  Assets/Astralization/Scripts/Player/InputHandler/ExorcismInputHandler.cs.meta
  Assets/Astralization/Scripts/Player/Inventory.cs
  Assets/Astralization/Scripts/UI/DialogueManager.cs
  Assets/Astralization/Scripts/UI/ExorcismBar.cs
  Assets/Astralization/Scripts/UI/ExorcismBar.cs.meta
  Assets/Astralization/Scripts/UI/HudManager.cs
  Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
  Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs.meta
  Assets/Astralization/Tests/InteractableTest/ExorcismTestScene.unity
  Assets/Astralization/Tests/InteractableTest/ExorcismTestScene.unity.meta
  Assets/Astralization/UI/ExorcismHud.meta
  Assets/Astralization/UI/ExorcismHud/ExorcismHud.prefab
  Assets/Astralization/UI/ExorcismHud/ExorcismHud.prefab.meta
  Assets/Astralization/UI/ItemHud/T_UI_LimeZu_48x48.png.meta
  Assets/InitTestScene637800458225327174.unity
  Assets/InitTestScene637800458225327174.unity.meta
  Assets/Input System/PlayerInputActions.inputactions
  Assets/_Developers/Vadim/Exorcism.unity
  Assets/_Developers/Vadim/Exorcism.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: Designing :books:, Programming :computer:

#209 [aesthetics] RV layout and its decor
  Assets/Astralization/Gameplay/HouseDecorations/Shelves/M_HD_Rack.meta
  Assets/Astralization/Gameplay/HouseDecorations/Shelves/M_HD_Rack.prefab
  Assets/Astralization/Gameplay/HouseDecorations/Shelves/M_HD_Rack.prefab.meta
  Assets/Astralization/Gameplay/HouseDecorations/Shelves/M_HD_Rack/Rack.asset
  Assets/Astralization/Gameplay/HouseDecorations/Shelves/M_HD_Rack/Rack.asset.meta
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk.meta
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk.prefab
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk.prefab.meta
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/Bottom.asset
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/Bottom.asset.meta
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/BottomDecor 1.asset
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/BottomDecor 1.asset.meta
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/BottomDecor.asset
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/BottomDecor.asset.meta
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/Top.asset
  Assets/Astralization/Gameplay/HouseDecorations/Tables/M_HD_CabinetDesk/Top.asset.meta
  Assets/Astralization/Gameplay/Structures/Nested.meta
  Assets/Astralization/Gameplay/Structures/Nested/RV.prefab
  Assets/Astralization/Gameplay/Structures/Nested/RV.prefab.meta
  Assets/_Developers/Jahns/HouseAbigail_Adjustment_Outdoor_withRV.unity
  Assets/_Developers/Jahns/HouseAbigail_Adjustment_Outdoor_withRV.unity.meta
Labels: Assets :art:, Designing :books:

#219 [refactor] Rename existing audio
  Assets/Astralization/Characters/Player/Audio/SFX_FemaleScream_1.mp3
  Assets/Astralization/Characters/Player/Audio/SFX_FemaleScream_1.mp3.meta
  Assets/Astralization/Characters/Player/Audio/SFX_Heartbeat_1_Loop.mp3
  Assets/Astralization/Characters/Player/Audio/SFX_Heartbeat_1_Loop.mp3.meta
  Assets/Astralization/Characters/Player/Audio/SFX_Heartbeat_2_Loop.mp3
  Assets/Astralization/Characters/Player/Audio/SFX_Heartbeat_2_Loop.mp3.meta
  Assets/Astralization/Characters/Player/Audio/SFX_Heartbeat_3_Loop.mp3
  Assets/Astralization/Characters/Player/Audio/SFX_Heartbeat_3_Loop.mp3.meta
  Assets/Astralization/Characters/Player/Audio/SFX_MaleScream_1.mp3
  Assets/Astralization/Characters/Player/Audio/SFX_MaleScream_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/Doors/SFX_DoorClose_1.mp3
  Assets/Astralization/Gameplay/Interactables/Doors/SFX_DoorClose_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/Doors/SFX_DoorOpen_1.mp3
  Assets/Astralization/Gameplay/Interactables/Doors/SFX_DoorOpen_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/SFX_AnkhActivate_1.mp3
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/SFX_AnkhActivate_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/SFX_AnkhDeactivate_1.mp3
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/SFX_AnkhDeactivate_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/Items/Flashlights/SFX_Flashlight_1.mp3
  Assets/Astralization/Gameplay/Interactables/Items/Flashlights/SFX_Flashlight_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/SFX_LightOff_1.mp3
  Assets/Astralization/Gameplay/Interactables/LightSwitches/SFX_LightOff_1.mp3.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/SFX_LightOn_1.mp3
  Assets/Astralization/Gameplay/Interactables/LightSwitches/SFX_LightOn_1.mp3.meta
Labels: Audio :headphones:

#221 [refactor] HM and GM
  Assets/Astralization/Scripts/Interactables/Controller/ClosetsController.cs
  Assets/Astralization/Scripts/Interactables/Controller/NpcController.cs
  Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
  Assets/Astralization/Scripts/Managers/GameManager.cs
  Assets/Astralization/Scripts/Managers/HudManager.cs
  Assets/Astralization/Scripts/Player/InputManager.cs
  Assets/Astralization/Scripts/UI/DialogueManager.cs
  Assets/Astralization/Scripts/UI/ExorcismBar.cs
Labels: Programming :computer:

#230 Sprite Gabriel
  Assets/Astralization/Characters/Player/Gabriel.meta
  Assets/Astralization/Characters/Player/Gabriel/T_CH_Gabriel.png
  Assets/Astralization/Characters/Player/Gabriel/T_CH_Gabriel.png.meta
Labels: Assets :art:
