Repository InShine-Studios/Horror-3D, pull requests merged in 2022-01, with the labels that each got.

#47 [feature] migrate player sprint
  Assets/Dev/Prefabs/Characters/Char 05.prefab
  Assets/Dev/Scenes/Default Dark.unity
  Assets/Dev/Scripts/Player/PlayerBase.cs
  Assets/Dev/Scripts/Player/PlayerMovement.cs
  Assets/Packages/Input System/PlayerInputActions.inputactions
Labels: Programming :computer:

#49 [feature] adding animation for sprint
  Assets/Dev/Scenes/Default Dark.unity
  Assets/Dev/Scripts/Player/PlayerAnimation.cs
  Assets/Dev/Scripts/Player/PlayerMovement.cs
Labels: Programming :computer:

#53 [Feature] adding icon for interactable item
  Assets/Arts/Textures/UI.meta
  Assets/Arts/Textures/UI/UI_48x48.png
  Assets/Arts/Textures/UI/UI_48x48.png.meta
  Assets/Dev/Prefabs/Characters/Char 05.prefab
  Assets/Dev/Prefabs/Interactables/LightSources/LightSwitch.prefab
  Assets/Dev/Scenes/Default Dark.unity
Labels: Programming :computer:

#54 [refactor] Split House Abigail Rooms with Probuilder and Progrid
  Assets/Dev/Scenes/House Abigail Wall.unity
  Assets/ProBuilder Data.meta
  Assets/ProBuilder Data/Default Color Palette.asset
  Assets/ProBuilder Data/Default Color Palette.asset.meta
  Assets/ProBuilder Data/Default Material Palette.asset
  Assets/ProBuilder Data/Default Material Palette.asset.meta
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: Designing :books:, Programming :computer:

#50 [feature][refactor] Migrate inventory, item. Refactor interact input action.
  Assets/Arts/Animations/Characters/Char 05/Char 05.controller
  Assets/Dev/Prefabs/Characters/Char 05.prefab
  Assets/Dev/Prefabs/Interactables/Items.meta
  Assets/Dev/Prefabs/Interactables/Items/DummyFlashlight.prefab
  Assets/Dev/Prefabs/Interactables/Items/DummyFlashlight.prefab.meta
  Assets/Dev/Scenes/Default Dark Interactable.unity
  Assets/Dev/Scenes/Default Dark Interactable.unity.meta
  Assets/Dev/Scenes/Default Dark Items.unity
  Assets/Dev/Scenes/Default Dark Items.unity.meta
  Assets/Dev/Scripts/Interactables/Controller/LightSwitchController.cs
  Assets/Dev/Scripts/Interactables/Item.meta
  Assets/Dev/Scripts/Interactables/Item/DummyFlashlight.cs
  Assets/Dev/Scripts/Interactables/Item/DummyFlashlight.cs.meta
  Assets/Dev/Scripts/Interactables/Item/Item.cs
  Assets/Dev/Scripts/Interactables/Item/Item.cs.meta
  Assets/Dev/Scripts/Player/Detectors/InteractableDetector.cs
  Assets/Dev/Scripts/Player/Detectors/ItemDetector.cs
  Assets/Dev/Scripts/Player/Detectors/ItemDetector.cs.meta
  Assets/Dev/Scripts/Player/Detectors/ObjectDetector.cs
  Assets/Dev/Scripts/Player/Inventory.cs
  Assets/Dev/Scripts/Player/Inventory.cs.meta
  Assets/Dev/Scripts/Utils/GeometryCalcu.cs
  Assets/Dev/Scripts/Utils/MathCalcu.cs
  Assets/Dev/Scripts/Utils/MathCalcu.cs.meta
  Assets/Packages/Input System/PlayerInputActions.inputactions
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
Labels: Programming :computer:

#56 Development
  Assets/Arts/Animations/Characters/Char 05/Char 05.controller
  Assets/Arts/Textures/UI.meta
  Assets/Arts/Textures/UI/UI_48x48.png
  Assets/Arts/Textures/UI/UI_48x48.png.meta
  Assets/Dev/Prefabs/Characters/Char 05.prefab
  Assets/Dev/Prefabs/Interactables/Items.meta
  Assets/Dev/Prefabs/Interactables/Items/DummyFlashlight.prefab
  Assets/Dev/Prefabs/Interactables/Items/DummyFlashlight.prefab.meta
  Assets/Dev/Prefabs/Interactables/LightSources/LightSwitch.prefab
  Assets/Dev/Scenes/Default Dark Interactable.unity
  Assets/Dev/Scenes/Default Dark Interactable.unity.meta
  Assets/Dev/Scenes/Default Dark Items.unity
  Assets/Dev/Scenes/Default Dark Items.unity.meta
  Assets/Dev/Scenes/House Abigail Wall.unity
  Assets/Dev/Scripts/Interactables/Controller/LightSwitchController.cs
  Assets/Dev/Scripts/Interactables/Item.meta
  Assets/Dev/Scripts/Interactables/Item/DummyFlashlight.cs
  Assets/Dev/Scripts/Interactables/Item/DummyFlashlight.cs.meta
  Assets/Dev/Scripts/Interactables/Item/Item.cs
  Assets/Dev/Scripts/Interactables/Item/Item.cs.meta
  Assets/Dev/Scripts/Player/Detectors/InteractableDetector.cs
  Assets/Dev/Scripts/Player/Detectors/ItemDetector.cs
  Assets/Dev/Scripts/Player/Detectors/ItemDetector.cs.meta
  Assets/Dev/Scripts/Player/Detectors/ObjectDetector.cs
  Assets/Dev/Scripts/Player/Inventory.cs
  Assets/Dev/Scripts/Player/Inventory.cs.meta
  Assets/Dev/Scripts/Player/PlayerAnimation.cs
  Assets/Dev/Scripts/Player/PlayerBase.cs
  Assets/Dev/Scripts/Player/PlayerMovement.cs
  Assets/Dev/Scripts/Utils/GeometryCalcu.cs
  Assets/Dev/Scripts/Utils/MathCalcu.cs
  Assets/Dev/Scripts/Utils/MathCalcu.cs.meta
  Assets/Packages/Input System/PlayerInputActions.inputactions
  Assets/ProBuilder Data.meta
  Assets/ProBuilder Data/Default Color Palette.asset
  Assets/ProBuilder Data/Default Color Palette.asset.meta
  Assets/ProBuilder Data/Default Material Palette.asset
  Assets/ProBuilder Data/Default Material Palette.asset.meta
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
Labels: Assets :art:, Audio :headphones:, Designing :books:, Programming :computer:

#76 [bugfix] Implement force grounding
  Assets/Dev/Prefabs/Characters/Char 05.prefab
  Assets/Dev/Scripts/Player/PlayerMovement.cs
Labels: Bug :no_entry:, Programming :computer:

#80 Implement Astral World Ambience
  Assets/Arts/Materials/Fog.meta
  Assets/Arts/Materials/Fog/Fog.mat
  Assets/Arts/Materials/Fog/Fog.mat.meta
  Assets/Arts/Materials/Fog/ParticleCloudWhite.png
  Assets/Arts/Materials/Fog/ParticleCloudWhite.png.meta
  Assets/Arts/Materials/PostProcessing.meta
  Assets/Arts/Materials/PostProcessing/VHS.mat
  Assets/Arts/Materials/PostProcessing/VHS.mat.meta
  Assets/Arts/Textures/Render.meta
  Assets/Arts/Textures/Render/VHS.renderTexture
  Assets/Arts/Textures/Render/VHS.renderTexture.meta
  Assets/Arts/Textures/Render/lowres.renderTexture
  Assets/Arts/Textures/Render/lowres.renderTexture.meta
  Assets/Dev/Prefabs/Cameras/Global Volume.prefab
  Assets/Dev/Prefabs/Cameras/Global Volume.prefab.meta
  Assets/Dev/Scenes/Duplicate Default Dark Interactable.meta
  Assets/Dev/Scenes/Duplicate Default Dark Interactable.unity
  Assets/Dev/Scenes/Duplicate Default Dark Interactable.unity.meta
  Assets/Dev/Scenes/Duplicate Default Dark Interactable/Global Volume Profile.asset
  Assets/Dev/Scenes/Duplicate Default Dark Interactable/Global Volume Profile.asset.meta
  Assets/Dev/Scenes/Duplicate Default Dark Interactable_Profiles.meta
  Assets/Dev/Scenes/Duplicate Default Dark Interactable_Profiles/PostProcess Profile 1.asset
  Assets/Dev/Scenes/Duplicate Default Dark Interactable_Profiles/PostProcess Profile 1.asset.meta
  Assets/Dev/Scenes/Duplicate Default Dark Interactable_Profiles/PostProcess Profile.asset
  Assets/Dev/Scenes/Duplicate Default Dark Interactable_Profiles/PostProcess Profile.asset.meta
  ProjectSettings/TagManager.asset
Labels: Designing :books:, Programming :computer:

#79 Added character spritesheet
  Assets/Arts/Textures/Characters/spr_player_iris.png
  Assets/Arts/Textures/Characters/spr_player_iris.png.meta
Labels: Assets :art:

#83 [feature] Adjust Light Switch SFX
  Assets/Dev/Prefabs/Interactables/LightSources/LightSwitch.prefab
  Assets/Dev/Scenes/Default Dark Interactable.unity
Labels: Audio :headphones:

#82 [aesthetics] add LightSwitch object
  Assets/Arts/Materials/LightSwitch.meta
  Assets/Arts/Materials/LightSwitch/Base.mat
  Assets/Arts/Materials/LightSwitch/Base.mat.meta
  Assets/Arts/Materials/LightSwitch/Switch.mat
  Assets/Arts/Materials/LightSwitch/Switch.mat.meta
  Assets/Dev/Prefabs/VoxelObjs/LightSwitch.prefab
  Assets/Dev/Prefabs/VoxelObjs/LightSwitch.prefab.meta
Labels: Assets :art:

#85 [feature] Implement Unity Testing
  Assets/Dev/Scripts/Interactables/Controller/LightSwitchController.cs
  Assets/Dev/Scripts/Interactables/Interactable.cs
  Assets/Dev/Scripts/Interactables/Item/DummyFlashlight.cs
  Assets/Dev/Scripts/Interactables/Item/Item.cs
  Assets/Dev/Scripts/Player/Inventory.cs
  Assets/Dev/Scripts/Player/PlayerBase.cs
  Assets/Dev/Scripts/Player/PlayerMovement.cs
  Assets/Dev/Scripts/Scripts.asmdef
  Assets/Dev/Scripts/Scripts.asmdef.meta
  Assets/Dev/Tests.meta
  Assets/Dev/Tests/IntegrationTests.asmdef
  Assets/Dev/Tests/IntegrationTests.asmdef.meta
  Assets/Dev/Tests/PlayerTest.cs
  Assets/Dev/Tests/PlayerTest.cs.meta
  Assets/Dev/Tests/TestScene.unity
  Assets/Dev/Tests/TestScene.unity.meta
  Packages/manifest.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: Programming :computer:

#106 Add Volumetric Fog to Global Volume prefab
  Assets/Dev/Prefabs/Cameras/Astral World Global Volume.prefab
  Assets/Dev/Prefabs/Cameras/Astral World Global Volume.prefab.meta
  Assets/Dev/Prefabs/Cameras/Global Volume.prefab
  Assets/Dev/Scenes/Vadim - Default Dark Interactable.unity
  Assets/Dev/Scenes/Vadim - Default Dark Interactable.unity.meta
Labels: Programming :computer:

#107 [feature] House Abigail Light Source
  Assets/Dev/Scenes/House Abigail Wall with Lighting.unity
  Assets/Dev/Scenes/House Abigail Wall with Lighting.unity.meta
Labels: Designing :books:, Programming :computer:

#111 [aesthetics] adjust SFX rolloff
  Assets/Dev/Prefabs/Interactables/Items/DummyFlashlight.prefab
  Assets/Dev/Prefabs/Interactables/LightSources/LightSwitch.prefab
Labels: Audio :headphones:, Programming :computer:

#110 [refactor] Rename audio files
  Assets/Audio/Sources/BGMs/MUS_ExploHouseAbigail_1_Loop.mp3
  Assets/Audio/Sources/BGMs/MUS_ExploHouseAbigail_1_Loop.mp3.meta
  Assets/Audio/Sources/BGMs/MUS_ListeningNpc_1_Loop.mp3
  Assets/Audio/Sources/BGMs/MUS_ListeningNpc_1_Loop.mp3.meta
  Assets/Audio/Sources/BGMs/MUS_Unused_1.mp3
  Assets/Audio/Sources/BGMs/MUS_Unused_1.mp3.meta
  Assets/Audio/Sources/BGMs/MUS_Unused_2.mp3
  Assets/Audio/Sources/BGMs/MUS_Unused_2.mp3.meta
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_DoorClose_1.mp3
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_DoorClose_1.mp3.meta
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_DoorOpen_1.mp3
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_DoorOpen_1.mp3.meta
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_Flashlight_1.mp3
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_Flashlight_1.mp3.meta
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_LightOff_1.mp3
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_LightOff_1.mp3.meta
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_LightOn_1.mp3
  Assets/Audio/Sources/Sound Effects/SFX_Gameplay_InanimateObject_LightOn_1.mp3.meta
Labels: Audio :headphones:, Programming :computer:

#116 [feature] Applying Hud
  Assets/Astralization/Gameplay/Interactables/Items/Flashlights/DummyFlashlight.prefab
  Assets/Astralization/Scripts/Interactables/Item/Item.cs
  Assets/Astralization/Scripts/Player/Inventory.cs
  Assets/Astralization/Scripts/UI.meta
  Assets/Astralization/Scripts/UI/ItemHud.cs
  Assets/Astralization/Scripts/UI/ItemHud.cs.meta
  Assets/Astralization/Tests/Interactable Tests/InteractableTest.cs
  Assets/Astralization/Tests/Interactable Tests/InteractableTestScene.unity
  Assets/Astralization/UI/ItemHud.meta
  Assets/Astralization/UI/ItemHud/ItemHud.prefab
  Assets/Astralization/UI/ItemHud/ItemHud.prefab.meta
  Assets/Astralization/UI/ItemHud/T_UI_LimeZu_48x48.png
  Assets/Astralization/UI/ItemHud/T_UI_LimeZu_48x48.png.meta
  Assets/_Developers/Naufal.meta
  Assets/_Developers/Naufal/Default Dark Items With Hud.unity
  Assets/_Developers/Naufal/Default Dark Items With Hud.unity.meta
Labels: Programming :computer:

#113 [aesthetics] Sofa & LightBulb
  Assets/Astralization/Gameplay/HouseDecorations.meta
  Assets/Astralization/Gameplay/HouseDecorations/Sofa.meta
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/MAT_Sofa_BrownFur_1.mat
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/MAT_Sofa_BrownFur_1.mat.meta
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/MAT_Sofa_WhiteFur_1.mat
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/MAT_Sofa_WhiteFur_1.mat.meta
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/M_HO_Sofa.prefab
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/M_HO_Sofa.prefab.meta
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/T_OBJ_Sofa_BrownFur_1.png
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/T_OBJ_Sofa_BrownFur_1.png.meta
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/T_OBJ_Sofa_WhiteFur_1.png
  Assets/Astralization/Gameplay/HouseDecorations/Sofa/T_OBJ_Sofa_WhiteFur_1.png.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/MAT_LightBulb_Base_1.mat
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/MAT_LightBulb_Base_1.mat.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/MAT_LightBulb_Bulb_1.mat
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/MAT_LightBulb_Bulb_1.mat.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/MAT_LightBulb_Holder_1.mat
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/MAT_LightBulb_Holder_1.mat.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/M_LS_LightBulb.prefab
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightBulb/M_LS_LightBulb.prefab.meta
  README.md
Labels: Assets :art:

#117 [aesthetics] adjust meshes size
  Assets/Astralization/Gameplay/Interactables/Doors/M_HO_Door.prefab
  Assets/Astralization/Gameplay/Interactables/LightSwitches/M_HO_LightSwitch.prefab
  Assets/Astralization/Gameplay/LightSources.meta
  Assets/Astralization/Gameplay/LightSources/CeilingLight.meta
  Assets/Astralization/Gameplay/LightSources/CeilingLight/MAT_CeilingLight_Base_1.mat
  Assets/Astralization/Gameplay/LightSources/CeilingLight/MAT_CeilingLight_Base_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/CeilingLight/MAT_CeilingLight_TubeEnd.mat
  Assets/Astralization/Gameplay/LightSources/CeilingLight/MAT_CeilingLight_TubeEnd.mat.meta
  Assets/Astralization/Gameplay/LightSources/CeilingLight/MAT_CeilingLight_Tube_1.mat
  Assets/Astralization/Gameplay/LightSources/CeilingLight/MAT_CeilingLight_Tube_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/CeilingLight/M_LS_CeilingLight.prefab
  Assets/Astralization/Gameplay/LightSources/CeilingLight/M_LS_CeilingLight.prefab.meta
  Assets/Astralization/Gameplay/LightSources/CeilingLight/M_LS_CeilingLight_TMP.prefab
  Assets/Astralization/Gameplay/LightSources/CeilingLight/M_LS_CeilingLight_TMP.prefab.meta
  Assets/Astralization/Gameplay/LightSources/LightBulb.meta
  Assets/Astralization/Gameplay/LightSources/LightBulb/MAT_LightBulb_Base_1.mat
  Assets/Astralization/Gameplay/LightSources/LightBulb/MAT_LightBulb_Base_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/LightBulb/MAT_LightBulb_Bulb_1.mat
  Assets/Astralization/Gameplay/LightSources/LightBulb/MAT_LightBulb_Bulb_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/LightBulb/MAT_LightBulb_Holder_1.mat
  Assets/Astralization/Gameplay/LightSources/LightBulb/MAT_LightBulb_Holder_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/LightBulb/M_LS_LightBulb.prefab
  Assets/Astralization/Gameplay/LightSources/LightBulb/M_LS_LightBulb.prefab.meta
  Assets/Astralization/Gameplay/LightSources/TableLight.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_Base_1.mat
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_Base_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_BraceBase_1.mat
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_BraceBase_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_BraceCore_1.mat
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_BraceCore_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_LightShade_1.mat
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_LightShade_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_Switch_1.mat
  Assets/Astralization/Gameplay/LightSources/TableLight/MAT_TableLight_Switch_1.mat.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/M_LS_TableLight.prefab
  Assets/Astralization/Gameplay/LightSources/TableLight/M_LS_TableLight.prefab.meta
  Assets/Astralization/Gameplay/LightSources/TableLight/M_LS_TableLight_TMP.prefab
  Assets/Astralization/Gameplay/LightSources/TableLight/M_LS_TableLight_TMP.prefab.meta
  Assets/_Developers/Jahns.meta
  Assets/_Developers/Jahns/HouseAbigail_Adjustment.unity
  Assets/_Developers/Jahns/HouseAbigail_Adjustment.unity.meta
Labels: Assets :art:

#133 [feature] Created Astral Meter Logic + Tests
  Assets/Astralization/Scripts/Party.meta
  Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
  Assets/Astralization/Scripts/Party/AstralMeterLogic.cs.meta
  Assets/Astralization/Tests/Interactable Tests/AstralTest.cs
  Assets/Astralization/Tests/Interactable Tests/AstralTest.cs.meta
  Assets/Astralization/Tests/Interactable Tests/AstralTestScene.unity
  Assets/Astralization/Tests/Interactable Tests/AstralTestScene.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: Programming :computer:

#132 [feature] Implement ankh item and testing for ankh
  Assets/Astralization/Characters/Iris/Iris.prefab
  Assets/Astralization/FX/AstralWorld/VOL_Global_AstralWorld_1.prefab
  Assets/Astralization/Gameplay/Interactables/Items/Ankh.meta
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/Ankh.prefab
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/Ankh.prefab.meta
  Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
  Assets/Astralization/Scripts/Interactables/Item/Ankh.cs.meta
  Assets/Astralization/Scripts/Utils/ColorHelper.cs
  Assets/Astralization/Scripts/Utils/ColorHelper.cs.meta
  Assets/Astralization/Tests/Interactable Tests/InteractableTest.cs
  Assets/Astralization/Tests/Interactable Tests/InteractableTestScene.unity
  Assets/Astralization/UI/ItemHud/T_UI_LimeZu_48x48.png.meta
  Assets/_Developers/Naufal/Item Ankh.unity
  Assets/_Developers/Naufal/Item Ankh.unity.meta
Labels: Programming :computer:

#142 [refactor] observer patterns
  Assets/Astralization/Audios/AudioManager.prefab
  Assets/Astralization/FX/AstralWorld/VOL_Global_AstralWorld_1.prefab
  Assets/Astralization/Gameplay/Interactables/Doors/Door.prefab
  Assets/Astralization/Gameplay/Interactables/Items/Ankh/Ankh.prefab
  Assets/Astralization/Gameplay/Interactables/Items/Flashlights/DummyFlashlight.prefab
  Assets/Astralization/Gameplay/Interactables/Items/OverworldItems.prefab
  Assets/Astralization/Gameplay/Interactables/Items/OverworldItems.prefab.meta
  Assets/Astralization/Gameplay/Interactables/LightSwitches/LightSwitch.prefab
  Assets/Astralization/Scripts/Interactables/Controller/DoorController.cs
  Assets/Astralization/Scripts/Interactables/Controller/LightSwitchController.cs
  Assets/Astralization/Scripts/Interactables/Interactable.cs
  Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
  Assets/Astralization/Scripts/Interactables/Item/DummyFlashlight.cs
  Assets/Astralization/Scripts/Interactables/Item/Item.cs
  Assets/Astralization/Scripts/Interactables/Item/OverworldItem.cs
  Assets/Astralization/Scripts/Interactables/Item/OverworldItem.cs.meta
  Assets/Astralization/Scripts/Player/Detectors/InteractableDetector.cs
  Assets/Astralization/Scripts/Player/Detectors/ItemDetector.cs
  Assets/Astralization/Scripts/Player/Inventory.cs
  Assets/Astralization/Scripts/States.meta
  Assets/Astralization/Scripts/States/AstralMeterLogic.cs
  Assets/Astralization/Scripts/States/AstralMeterLogic.cs.meta
  Assets/Astralization/Scripts/States/VolumeAstral.cs
  Assets/Astralization/Scripts/States/VolumeAstral.cs.meta
  Assets/Astralization/Scripts/UI/ItemHud.cs
  Assets/Astralization/Scripts/UI/ItemLogo.cs
  Assets/Astralization/Scripts/UI/ItemLogo.cs.meta
  Assets/Input System/PlayerInputActions.inputactions
  Assets/_Developers/Dean/Refactor Observer Pattern.unity
  Assets/_Developers/Dean/Refactor Observer Pattern.unity.meta
  Assets/_Developers/Naufal/Item Ankh.unity
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Programming :computer:

#141 [feature] Adjust MUS_HouseAbigail_1_Loop to intended usage
  Assets/Astralization/Audios/Exploration/MUS_HouseAbigail_1_Loop.mp3
  Assets/Astralization/Audios/Exploration/MUS_HouseAbigail_1_Loop.mp3.meta
  Assets/Astralization/Audios/Lobby.meta
  Assets/Astralization/Audios/Lobby/MUS_Lobby_1_Loop.mp3
  Assets/Astralization/Audios/Lobby/MUS_Lobby_1_Loop.mp3.meta
  Assets/Astralization/Audios/Unused/MUS_Unused_3.mp3
  Assets/Astralization/Audios/Unused/MUS_Unused_3.mp3.meta
Labels: Audio :headphones:
