Repository InShine-Studios/Horror-3D, pull requests merged in 2022-08, with the labels that each got.

#388 Map Changes
  Assets/Astralization/Gameplay/Interactables/Doors/Door.prefab
  Assets/Astralization/Resources/Stages/Building - StagePoint.asset
  Assets/_Developers/Raihan/HouseAbigail_FixedBuilding 1.unity
  Assets/_Developers/Raihan/HouseAbigail_FixedBuilding 1.unity.meta
  Assets/_Developers/Vadim/HouseAbigail_FixedBuilding 1.unity
  Assets/_Developers/Vadim/HouseAbigail_FixedBuilding 1.unity.meta
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: Designing :books:

#385 [feature] timeslot
  Assets/Astralization/Characters/Player/PlayerHudCanvas.prefab
  Assets/Astralization/Gameplay/GameStates/TimeslotManager.prefab
  Assets/Astralization/Gameplay/GameStates/TimeslotManager.prefab.meta
  Assets/Astralization/Gameplay/GameStates/WorldManager.prefab
  Assets/Astralization/Gameplay/Interactables/DummyTimeslotChanger.meta
  Assets/Astralization/Gameplay/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.prefab
  Assets/Astralization/Gameplay/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.prefab.meta
  Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger.meta
  Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.cs
  Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.cs.meta
  Assets/Astralization/Scripts/Managers/GameManager.cs
  Assets/Astralization/Scripts/Managers/HudManager.cs
  Assets/Astralization/Scripts/States/TimeslotState.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotAfternoonState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotAfternoonState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotEveningState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotEveningState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotInitState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotInitState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotMorningState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotMorningState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotStateMachine.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotStateMachine.cs.meta
  Assets/Astralization/Scripts/UI/TimeslotHud.cs
  Assets/Astralization/Scripts/UI/TimeslotHud.cs.meta
  Assets/Astralization/Scripts/Utils/Helper/UiHelper.cs
  Assets/Astralization/Tests/StateTest/TimeslotTest.cs
  Assets/Astralization/Tests/StateTest/TimeslotTest.cs.meta
  Assets/Astralization/Tests/StateTest/TimeslotTestScene.unity
  Assets/Astralization/Tests/StateTest/TimeslotTestScene.unity.meta
  Assets/Astralization/UI/ItemHud/T_UI_LimeZu_48x48.png.meta
  Assets/Astralization/UI/TimeslotHud.meta
  Assets/Astralization/UI/TimeslotHud/AC_Timeslot_Hud.controller
  Assets/Astralization/UI/TimeslotHud/AC_Timeslot_Hud.controller.meta
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Afternoon.anim
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Afternoon.anim.meta
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Evening.anim
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Evening.anim.meta
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Morning.anim
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Morning.anim.meta
  Assets/Astralization/UI/TimeslotHud/TimeslotHud.prefab
  Assets/Astralization/UI/TimeslotHud/TimeslotHud.prefab.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: Programming :computer:

#389 [rework] player camera
  Assets/Astralization/Characters/Player/Player.prefab
  Assets/Astralization/_Levels/_General/Player Follow.prefab
Labels: Programming :computer:

#396 Sprint 25
  Assets/Astralization/Characters/Player/Player.prefab
  Assets/Astralization/Characters/Player/PlayerHudCanvas.prefab
  Assets/Astralization/Gameplay/GameStates/TimeslotManager.prefab
  Assets/Astralization/Gameplay/GameStates/TimeslotManager.prefab.meta
  Assets/Astralization/Gameplay/GameStates/WorldManager.prefab
  Assets/Astralization/Gameplay/Interactables/Doors/Door.prefab
  Assets/Astralization/Gameplay/Interactables/DummyTimeslotChanger.meta
  Assets/Astralization/Gameplay/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.prefab
  Assets/Astralization/Gameplay/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.prefab.meta
  Assets/Astralization/Resources/Stages/Building - StagePoint.asset
  Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger.meta
  Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.cs
  Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.cs.meta
  Assets/Astralization/Scripts/Managers/GameManager.cs
  Assets/Astralization/Scripts/Managers/HudManager.cs
  Assets/Astralization/Scripts/States/TimeslotState.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotAfternoonState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotAfternoonState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotEveningState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotEveningState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotInitState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotInitState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotMorningState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotMorningState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotState.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotState.cs.meta
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotStateMachine.cs
  Assets/Astralization/Scripts/States/TimeslotState/TimeslotStateMachine.cs.meta
  Assets/Astralization/Scripts/UI/TimeslotHud.cs
  Assets/Astralization/Scripts/UI/TimeslotHud.cs.meta
  Assets/Astralization/Scripts/Utils/Helper/UiHelper.cs
  Assets/Astralization/Tests/StateTest/TimeslotTest.cs
  Assets/Astralization/Tests/StateTest/TimeslotTest.cs.meta
  Assets/Astralization/Tests/StateTest/TimeslotTestScene.unity
  Assets/Astralization/Tests/StateTest/TimeslotTestScene.unity.meta
  Assets/Astralization/UI/ItemHud/T_UI_LimeZu_48x48.png.meta
  Assets/Astralization/UI/TimeslotHud.meta
  Assets/Astralization/UI/TimeslotHud/AC_Timeslot_Hud.controller
  Assets/Astralization/UI/TimeslotHud/AC_Timeslot_Hud.controller.meta
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Afternoon.anim
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Afternoon.anim.meta
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Evening.anim
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Evening.anim.meta
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Morning.anim
  Assets/Astralization/UI/TimeslotHud/A_Timeslot_Morning.anim.meta
  Assets/Astralization/UI/TimeslotHud/TimeslotHud.prefab
  Assets/Astralization/UI/TimeslotHud/TimeslotHud.prefab.meta
  Assets/Astralization/_Levels/_General/Player Follow.prefab
  Assets/_Developers/Raihan/HouseAbigail_FixedBuilding 1.unity
  Assets/_Developers/Raihan/HouseAbigail_FixedBuilding 1.unity.meta
  Assets/_Developers/Vadim/HouseAbigail_FixedBuilding 1.unity
  Assets/_Developers/Vadim/HouseAbigail_FixedBuilding 1.unity.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: Assets :art:, Designing :books:, Documentation :memo:, Programming :computer:
